# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hw1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hw1
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SwiftyJSON'
  pod 'PromiseKit'
end
